# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efe3c685b3e9e1c3da1b9d8c82105e5d955127e17964da5e17fb72cedbb2e06d0195bf766229cc36c3ecd5dcb86b03a4244689143590ab20eb8707ef00e79d47

test:
  secret_key_base: f300967360311de0801a2f77791ef7a0c297278766f316e154f89043928a42409aec7a8c7e82009fa7dff94f5a62fab45d97c437836e10b91293f2c0baa6f3c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
